### ISSUE TITLE
Missing friendly name for "hhw_collect"

### ISSUE THREAD

**Issue by superm1** [bachya/aiorecollect#12]
**Describe the bug**
I'm currently using recollect waste via Home Assistant.  Recently I've been noticing that my automations that used it are including a new pickup type "hhw_collect".

I'd like to get a friendly name into this if possible.

**To Reproduce**
1. Configure a location using place `740E04F6-D678-11E6-AAA5-549294E6FE1C` and service id `323`
2. Observe that future pickups have `hhw_collect`

**Expected behavior**
I was expecting that to be "Household Hazardous Waste" (which is described here: http://www.austintexas.gov/faq/what-items-are-accepted-recycle-reuse-drop-center#overlay-context=department/austin-resource-recovery/faq)

**Screenshots**
![image](https://user-images.githubusercontent.com/494526/107184694-aba2e880-69a6-11eb-80be-34fc44a7a477.png)

**Additional context**

**Comment by superm1** [comment]
BTW though, looking at the [JSON ](https://api.recollect.net/api/places/740E04F6-D678-11E6-AAA5-549294E6FE1C/services/323/events) maybe it's not Household hazardous waste, but just a general pickup notification.  I notice the icon is null as are all the messages.  Could you maybe just filter it from the library side with a heuristic?

**Comment by bachya** [comment]
Unfortunately, this is not an issue that can be fixed in this library. As you already noted, the data returned doesn't contain a friendly name for this pickup type:

```json
{
  "area_name": "Austin",
  "is_week_long": 0,
  "sort_order": 0,
  "short_text_message": null,
  "icon": "",
  "backgroundColor": "#5FAE47",
  "borderColor": "#5FAE47",
  "html_message": "",
  "voice_message": null,
  "name": "hhw_collect",
  "service_name": "waste",
  "event_type": "pickup",
  "opts": {
    "event_proto": {
      "calendar_only": 1,
      "bic_slot_count": 9999,
      "reminder_only": 1
    },
    "event_type": "pickup"
  },
  "color": "#5FAE47",
  "plain_text_message": null,
  "id": 12898,
  "icon_uri_fragment": null,
  "subject": null
}
```

**Comment by superm1** [comment]
Ok thanks.

FWIW I contacted recollect to inquire about this. They said:

```
You can safely ignore that event in your application. It is related to how the city implements Household Hazardous Waste collections.
```

So I guess if you would still prefer not to filter here I'll just filter in my use.
